global:
  engine:
    image: radius.azurecr.io/deployment-engine
    tag: 07d2f30cf1f465a46ede17ce7f4cd48ca4272fad
  extensibility:
    image: radius.azurecr.io/bicep-extensibility
    tag: latest
  radius:
    container: radius.azurecr.io/radius-controller
    tag: latest # Tag for radius-controller image.
