global:
  engine:
    image: radius.azurecr.io/deployment-engine
    tag: b792418e0dd01ce9979177806fc06158bdb64a1b
  extensibility:
    image: radius.azurecr.io/bicep-extensibility
    tag: latest
  radius:
    container: radius.azurecr.io/radius-controller
    tag: latest # Tag for radius-controller image.
