global:
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
  #
  # Configure global.zipkin.url to enable distributed trace. Replace the example url
  # below with the environment specific url
  # zipkin:
  #   url: "http://jaeger-collector.radius-monitoring.svc.cluster.local:9411/api/v2/spans"
  #
controller:
  image: rynowak.azurecr.io/controller
  tag: kubernetes-private
  resources:
    requests:
      memory: "60Mi"
    limits:
      memory: "300Mi"

de:
  image: radius.azurecr.io/deployment-engine
  # Default tag uses Chart AppVersion.
  # tag: latest
  resources:
    requests:
      # request memory is the average memory usage + 10% buffer.
      memory: "130Mi"
    limits:
      memory: "300Mi"

ucp:
  image: rynowak.azurecr.io/ucpd
  tag: kubernetes-private
  # Default tag uses Chart AppVersion.
  # tag: latest
  resources:
    requests:
      # request memory is the average memory usage + 10% buffer.
      memory: "60Mi"
    limits:
      memory: "300Mi"

rp:
  image: rynowak.azurecr.io/applications-rp
  tag: kubernetes-private
  publicEndpointOverride: ""
  resources:
    requests:
      # request memory is the average memory usage + 10% buffer.
      memory: "160Mi"
    limits:
      # limit is higher for applications-rp because the Terraform execution
      # can spike memory usage.
      memory: "500Mi"
  terraform:
    path: "/terraform"
