de:
  image: radius.azurecr.io/deployment-engine
  tag: latest
ucp:
  image: radius.azurecr.io/ucpd
  tag: latest # Tag for ucp image.
global:
  rp:
    image: radius.azurecr.io/appcore-rp
    tag: latest # Tag for appcore-rp image.
    provider:
      azure: {}
    publicEndpointOverride: ""
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
