de:
  image: radius.azurecr.io/deployment-engine
  tag: latest
ucp:
  image: radius.azurecr.io/ucpd
  tag: latest 
  provider:
    azure: {}
  #  aws: 
  #    region:"us-east"
rp:
  image: radius.azurecr.io/appcore-rp
  tag: latest
  publicEndpointOverride: ""
global:
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
