name: store
stages:
- name: infra
  bicep:
    template: iac/infra.bicep
- name: app
  build:
    build_step:
      docker:
        context: node-service
        image: test/node-service
  bicep:
    template: iac/app.bicep