name: Generate reference docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - release/*

jobs:
  reference-docs:
    name: Generate and PR reference documentation
    runs-on: ubuntu-latest
    env:
      GOVER: '^1.21'
      GOPRIVATE: github.com/radius-project
    steps:
      - name: Checkout radius repository
        uses: actions/checkout@v3
        with:
          repository: radius-project/radius
          path: radius
      - name: Parse release version and set environment variables
        run: python radius/.github/scripts/get_release_version.py
      - name: Generate docs release branch name
        run: |
          if [[ ${{ env.REL_CHANNEL }} != "edge" ]]; then
            echo DOCS_BRANCH="v${{ env.REL_CHANNEL }}" >> $GITHUB_ENV
          else
            echo DOCS_BRANCH="edge" >> $GITHUB_ENV
          fi
      - name: Checkout docs repository
        uses: actions/checkout@v3
        with:
          repository: radius-project/docs
          path: docs
          ref: ${{ env.DOCS_BRANCH }}
          token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
      # Copy and upload resource reference docs
      - name: Copy resource reference docs into docs repo
        run: |
          mkdir -p docs/docs/snippets/resource-docs/
          export RESOURCE_DOCS=$(find radius/hack/bicep-types-radius/generated/ -type f -name '*.md' -print0 | xargs -0)
          for file in $RESOURCE_DOCS; do
            fileTarget=${file#radius/hack/bicep-types-radius/generated/}
            echo Copying $file to docs/docs/snippets/resource-docs/$fileTarget
            cp -p $file docs/docs/snippets/resource-docs/$fileTarget
          done
      - name: Upload resource reference docs
        uses: actions/upload-artifact@v3
        with:
          name: resource-docs
          path: docs/docs/snippets/resource-docs
      # Generate and upload CLI docs
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVER }}
          cache-dependency-path: radius/go.sum
      - name: Generate CLI docs
        run: |
            find docs/docs/content/reference/cli -type f ! -name '_index.md' -delete
            cd radius
            go run cmd/docgen/main.go ../docs/docs/content/reference/cli
      - name: Upload CLI docs
        uses: actions/upload-artifact@v3
        with:
          name: cli-docs
          path: docs/docs/content/reference/cli
      # Open PR against docs repository
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        if: github.event_name != 'pull_request'
        with:
          token: ${{ secrets.GH_RAD_CI_BOT_PAT }}
          path: docs
          add-paths: |
            *.md
          committer: rad-ci-bot <rad-ci-bot@users.noreply.github.com>
          author: rad-ci-bot <rad-ci-bot@users.noreply.github.com>
          branch: reference-cli/patch-${{ github.sha }}
          delete-branch: true
          title: |
            Update rad CLI documentation
          body: |
            ## Autogenerated PR
            
            This PR updates the rad CLI reference documentation.

            GitHub SHA: ${{ github.sha }}
          commit-message: |
            Autogenerate rad CLI reference docs
